### ISSUE TITLE
IR modal LOV with multiple pages

### ISSUE THREAD

**Issue by sgiera** [Saeed-Hassanpour/ModalLOVIG#3]
I am using apex 5.1.2 and using your plugin. I can click on a row in the IR modal LOV and it returns a row. Great! However, if I search on a value in the IR modal LOV (LOV has 1000 rows on multiple pages) the search works but when I click on a row after the search it seems the modal is locked up and nothing happens. It does not return a row.  Any idea?

**Comment by sgiera** [comment]
I can close the modal after the search using the X in right hand corner, open it back up, and then click on a value and it works.  It seems like it is a search issue with interactive report that has multiples pages.

Thanks,
sgiera

**Comment by sgiera** [comment]
This problem has been fixed.  I had the event scope attribute set incorrectly.

**Comment by Saeed-Hassanpour** [comment]
he had the event scope attribute set incorrectly
